name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          set -e
          cd /home/boshadmin

          # Agar loyiha yo'q bo‘lsa, klon qilamiz
          if [ ! -d "ifoda-web" ]; then
              git clone https://github.com/IfodaAI/ifoda_web.git
          fi

          cd ifoda-web

          # Agar .git mavjud bo‘lsa, yangilaymiz
          if [ -d ".git" ]; then
              git pull origin main
          fi

          # Python virtual muhitni tekshiramiz
          if [ ! -d "base" ]; then
              python3 -m venv base
          fi

          source base/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          python manage.py migrate

          # Parolsiz sudo ishlashi kerak
          sudo systemctl restart ifoda_web.service
          EOF
