- name: Deploy to Server
  run: |
    ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
    set -e
    cd /home/boshadmin

    cd ifoda_web

    if [ ! -d "base" ]; then
        python3 -m venv base
    fi

    source base/bin/activate
    pip install --upgrade pip
    pip install -r requirements.txt
    python manage.py migrate

    sudo systemctl restart ifoda_web.service
    EOF
